### ISSUE TITLE
Issues when compiling

### ISSUE THREAD

**Issue by dkappe** [cvuorinen/angular-excel#1]
When attempting to compile, we get:

app/spreadsheet.ts(31,23): error TS2339: Property 'evilEval' does not exist on type 'Window'.
node_modules/angular2/src/facade/promise.d.ts(1,10): error TS2661: Cannot re-export name that is not defined in the module.
app/cell.ts(40,22): error TS2461: Type '{}' is not an array type.

**Comment by cvuorinen** [comment]
I'll have to check into this again, I fixed the evilEval issue already with this: https://github.com/cvuorinen/angular2-excel/blob/master/app/spreadsheet.ts#L32
But have to check if it's still not working. Don't remember seeing that "Type '{}' is not an array type." before.

What ts version are you using?

**Comment by cvuorinen** [comment]
@dkappe these are fixed now with the latest commits.
